name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Scope for Maven Action
        uses: undefinedlabs/scope-for-maven-action@beta
        with:
          dsn: ${{secrets.SCOPE_DSN}}
        env:
          SCOPE_CODE_PATH_ENABLED: true
          SCOPE_CODE_PATH_BASE_PACKAGES: "com.undefinedlabs.scope"
          SCOPE_INSTRUMENTATION_DB_STATEMENT_VALUES: true
          SCOPE_INSTRUMENTATION_HTTP_PAYLOADS: true
          SCOPE_LOGGER_ROOT: /home/runner/work/java-demo-client/java-demo-client/logs
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: scopelogs
          path: /home/runner/work/java-demo-client/java-demo-client/logs
